In [12]:
l=[1,0,3,4,0,8]
j=0
for i in range(len(l)):
    if l[i]!=0:
        l[j],l[i]=l[i],l[j]
        j+=1
print(l)

[1, 3, 4, 8, 0, 0]

In [13]:
class Math :
    def add(self,a=1,b=1,c=1,d=1):
        print(a*b*c*d)
obj=Math()

In [14]:
obj.add(1,4)

4

In [15]:
def sam():
    print("overwriting")
mid=sam    #monkey patching(storing method address to a variable)
def sam(a,b,c):#method overloading
    print(a*b*c)

In [16]:
mid()
sam(1,2,3)

overwriting
6

In [17]:
class Person:
    def printp(p):
        print(p)
class Student(Person):
    def printp(p,s):
        print(p,s)
p=Person.printp('sampad')
s=Student.printp('sampadcse',18)

sampad
sampadcse 18

In [18]:
class A:
    def __init__(self,a):
        self.a=a
    def __add__(self, other):
        return self.a+other.a
    def __sub__(self, other):
        return self.a-other.a
obj1=A(10)
obj2=A(20)
print(obj1+obj2)#internally calls def __add__ function
print(obj1-obj2)#internally calls def __sub__ function

30
-10

In [19]:
class Vehicle:
    def __init__(self,veh_id,brand):
        self.veh_id=veh_id
        self.brand=brand
    def calculate_rent(self,r):
        if r=='Car':
            print("rent on basis of days")
        elif r=='Bike':
            print("rent on basis of hour")
        else:
            print("rent on basis of km")
        
class Car(Vehicle):
    def __init__(self, veh_id, brand,ppd):
        super().__init__(veh_id, brand)
        self.ppd=ppd
    def calculate_rent(self, r):
        print("Rent:",r*self.ppd)
class Bike(Vehicle):
    def __init__(self, veh_id, brand,pph):
        super().__init__(veh_id, brand)
        self.pph=pph
    def calculate_rent(self, r):
        print("Rent:",r*self.pph)
class Truck(Vehicle):
    def __init__(self, veh_id, brand,ppk):
        super().__init__(veh_id, brand)
        self.ppk=ppk
    def calculate_rent(self, r):
        print("Rent:",r*self.ppk)
car=Truck(1,'suzuki',6000)
car.calculate_rent(9)

Rent: 54000

In [20]:
import pandas as pd
df=pd.read_csv(r'C:\Users\91983\Desktop\PYTHON\Wine_Quality\wineQT.csv')
df.head(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,3
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,4

In [21]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\91983\onedrive\documents\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\91983\onedrive\documents\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\91983\onedrive\documents\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\91983\onedrive\documents\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\91983\onedrive\documents\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\91983\onedrive\documents\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [22]:
import pandas as pd

In [23]:
s=pd.Series([10,20,30])
s+5

0    15
1    25
2    35
dtype: int64

In [24]:
type(s)

pandas.core.series.Series

In [25]:
p=pd.Series([10,20,30],index=['a','b','c'])
p

a    10
b    20
c    30
dtype: int64

In [26]:
pd.Series({1:'sampad',2:'rohan'})

1    sampad
2     rohan
dtype: object

In [27]:
#series properties
s.values

array([10, 20, 30], dtype=int64)

In [28]:
p.index

Index(['a', 'b', 'c'], dtype='object')

In [29]:
p.size

3

In [30]:
p.dtype

dtype('int64')

In [31]:
p.mean()

20.0

In [32]:
print(p.max())
print(p.min())
print(p.std())
print(p.sum())
print(p.value_counts())

30
10
10.0
60
10    1
20    1
30    1
Name: count, dtype: int64

In [33]:
a=pd.DataFrame(([1,2],[3,4]),[5,6])
a

   0  1
5  1  2
6  3  4

In [34]:
type(a)

pandas.core.frame.DataFrame

In [35]:
pd.DataFrame({'A':[1,2],'B':[3,4]})

   A  B
0  1  3
1  2  4

In [36]:
df=pd.read_csv(r'C:\Users\91983\Desktop\PYTHON\Wine_Quality\wineQT.csv')
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [37]:
df.head(5)#it can be written head(-1139) as the head will start from the first row and will go to the -1139 th row as there are 1142 values

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,3
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,4

In [38]:
df.tail(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [39]:
df.sample(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
463,9.4,0.33,0.59,2.8,0.079,9.0,30.0,0.99760,3.12,0.54,12.0,6,653
767,11.6,0.41,0.54,1.5,0.095,22.0,41.0,0.99735,3.02,0.76,9.9,7,1088
644,9.1,0.28,0.46,9.0,0.114,3.0,9.0,0.99901,3.18,0.60,10.9,6,911
479,8.6,0.80,0.11,2.3,0.084,12.0,31.0,0.99790,3.40,0.48,9.9,5,677
564,10.0,0.56,0.24,2.2,0.079,19.0,58.0,0.99910,3.18,0.56,10.1,6,787

In [40]:
df.loc[10:21]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
10,5.6,0.615,0.00,1.6,0.089,16.0,59.0,0.9943,3.58,0.52,9.9,5,12
11,7.8,0.610,0.29,1.6,0.114,9.0,29.0,0.9974,3.26,1.56,9.1,5,13
12,8.5,0.280,0.56,1.8,0.092,35.0,103.0,0.9969,3.30,0.75,10.5,7,16
13,7.9,0.320,0.51,1.8,0.341,17.0,56.0,0.9969,3.04,1.08,9.2,6,19
14,7.6,0.390,0.31,2.3,0.082,23.0,71.0,0.9982,3.52,0.65,9.7,5,21
15,7.9,0.430,0.21,1.6,0.106,10.0,37.0,0.9966,3.17,0.91,9.5,5,22
16,8.5,0.490,0.11,2.3,0.084,9.0,67.0,0.9968,3.17,0.53,9.4,5,23
17,6.9,0.400,0.14,2.4,0.085,21.0,40.0,0.9968,3.43,0.63,9.7,6,24
18,6.3,0.390,0.16,1.4,0.080,11.0,23.0,0.9955,3.34,0.56,9.3,5,25
19,7.6,0.410,0.24,1.8,0.080,4.0,11.0,0.9962,3.28,0.59,9.5,5,26
20,7.1,0.710,0.00,1.9,0.080,14.0,35.0,0.9972,3.47,0.55,9.4,5,28
21,7.8,0.645,0.00,2.0,0.082,8.0,16.0,0.9964,3.38,0.59,9.8,6,29

In [41]:
df.ndim

2

In [42]:
df.shape

(1143, 13)

In [43]:
df.size

14859

In [44]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'Id'],
      dtype='object')

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64
 12  Id                    1143 non-null   int64
dtypes: float64(11), int64(2)
memory usage: 116.2 KB

In [46]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
count,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000
mean,8.311111,0.531339,0.268364,2.532152,0.086933,15.615486,45.914698,0.996730,3.311015,0.657708,10.442111,5.657043,804.969379
std,1.747595,0.179633,0.196686,1.355917,0.047267,10.250486,32.782130,0.001925,0.156664,0.170399,1.082196,0.805824,463.997116
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000,0.000000
25%,7.100000,0.392500,0.090000,1.900000,0.070000,7.000000,21.000000,0.995570,3.205000,0.550000,9.500000,5.000000,411.000000
50%,7.900000,0.520000,0.250000,2.200000,0.079000,13.000000,37.000000,0.996680,3.310000,0.620000,10.200000,6.000000,794.000000
75%,9.100000,0.640000,0.420000,2.600000,0.090000,21.000000,61.000000,0.997845,3.400000,0.730000,11.100000,6.000000,1209.500000
max,15.900000,1.580000,1.000000,15.500000,0.611000,68.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000,1597.000000

In [47]:
df['quality'].value_counts(sort=True,ascending=True)

quality
3      6
8     16
4     33
7    143
6    462
5    483
Name: count, dtype: int64

In [48]:
df.describe(include=float)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
count,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000
mean,8.311111,0.531339,0.268364,2.532152,0.086933,15.615486,45.914698,0.996730,3.311015,0.657708,10.442111
std,1.747595,0.179633,0.196686,1.355917,0.047267,10.250486,32.782130,0.001925,0.156664,0.170399,1.082196
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000
25%,7.100000,0.392500,0.090000,1.900000,0.070000,7.000000,21.000000,0.995570,3.205000,0.550000,9.500000
50%,7.900000,0.520000,0.250000,2.200000,0.079000,13.000000,37.000000,0.996680,3.310000,0.620000,10.200000
75%,9.100000,0.640000,0.420000,2.600000,0.090000,21.000000,61.000000,0.997845,3.400000,0.730000,11.100000
max,15.900000,1.580000,1.000000,15.500000,0.611000,68.000000,289.000000,1.003690,4.010000,2.000000,14.900000

In [49]:
df.describe(include=int)

           quality           Id
count  1143.000000  1143.000000
mean      5.657043   804.969379
std       0.805824   463.997116
min       3.000000     0.000000
25%       5.000000   411.000000
50%       6.000000   794.000000
75%       6.000000  1209.500000
max       8.000000  1597.000000

In [50]:
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
Id                        int64
dtype: object

In [51]:
df.alcohol.dtypes

dtype('float64')

In [52]:
df['fixed acidity'].dtype

dtype('float64')

In [53]:
df.select_dtypes(include=int)

      quality    Id
0           5     0
1           5     1
2           5     2
3           6     3
4           5     4
...       ...   ...
1138        6  1592
1139        6  1593
1140        5  1594
1141        6  1595
1142        5  1597

[1143 rows x 2 columns]

In [54]:
df.select_dtypes(include=int).columns # if we write exclude instead of include there will be showing the columns which are not int

Index(['quality', 'Id'], dtype='object')

In [55]:
df.iloc[0:2,0:9]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH
0,7.4,0.70,0.0,1.9,0.076,11.0,34.0,0.9978,3.51
1,7.8,0.88,0.0,2.6,0.098,25.0,67.0,0.9968,3.20

In [56]:
df['fixed acidity'][0]

7.4

In [57]:
df.iat[0,3]

1.9

In [58]:
df.isnull()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,False,False,False,False,False,False,False,False,False,False,False,False,False
1139,False,False,False,False,False,False,False,False,False,False,False,False,False
1140,False,False,False,False,False,False,False,False,False,False,False,False,False
1141,False,False,False,False,False,False,False,False,False,False,False,False,False
1142,False,False,False,False,False,False,False,False,False,False,False,False,False

In [59]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

In [60]:
df.notnull().sum()

fixed acidity           1143
volatile acidity        1143
citric acid             1143
residual sugar          1143
chlorides               1143
free sulfur dioxide     1143
total sulfur dioxide    1143
density                 1143
pH                      1143
sulphates               1143
alcohol                 1143
quality                 1143
Id                      1143
dtype: int64

In [61]:
df.dropna() # drop all the missing values

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [62]:
df.fillna(0)  #fill the missing values with 0

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [63]:
df.fillna(df.mean)  # fill the missing data with the mean value

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [64]:
df.duplicated() # checks the duplicate data in the dataset
#df.duplicated().sum()

0       False
1       False
2       False
3       False
4       False
        ...
1138    False
1139    False
1140    False
1141    False
1142    False
Length: 1143, dtype: bool

In [65]:
df.sort_values(by='alcohol')

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
368,10.4,0.61,0.49,2.1,0.200,5.0,16.0,0.99940,3.16,0.63,8.4,3,517
388,14.3,0.31,0.74,1.8,0.075,6.0,15.0,1.00080,2.86,0.79,8.4,6,544
1023,10.0,0.38,0.38,1.6,0.169,27.0,90.0,0.99914,3.15,0.65,8.5,5,1436
263,7.9,0.24,0.40,1.6,0.056,11.0,25.0,0.99670,3.32,0.87,8.7,6,371
1053,9.9,0.50,0.50,13.8,0.205,48.0,82.0,1.00242,3.16,0.75,8.8,5,1476
...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,5.2,0.34,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.0,6,142
98,5.2,0.34,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.0,6,144
589,4.9,0.42,0.00,2.1,0.048,16.0,42.0,0.99154,3.71,0.74,14.0,7,821
419,5.0,0.42,0.24,2.0,0.060,19.0,50.0,0.99170,3.72,0.74,14.0,8,588
462,15.9,0.36,0.65,7.5,0.096,22.0,71.0,0.99760,2.98,0.84,14.9,5,652

In [66]:
df.sample(5).sort_index()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
32,4.6,0.520,0.15,2.1,0.054,8.0,65.0,0.99340,3.90,0.56,13.1,4,45
95,8.4,0.745,0.11,1.9,0.090,16.0,63.0,0.99650,3.19,0.82,9.6,5,140
208,8.7,0.520,0.09,2.5,0.091,20.0,49.0,0.99760,3.34,0.86,10.6,7,290
713,8.9,0.380,0.40,2.2,0.068,12.0,28.0,0.99486,3.27,0.75,12.6,7,1016
970,7.3,0.740,0.08,1.7,0.094,10.0,45.0,0.99576,3.24,0.50,9.8,5,1366

In [67]:
df.sample(5,ignore_index=False).sort_index(ascending=True)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
201,8.9,0.40,0.32,5.60,0.087,10.0,47.0,0.99910,3.38,0.77,10.5,7,283
328,10.3,0.50,0.42,2.00,0.069,21.0,51.0,0.99820,3.16,0.72,11.5,6,466
356,10.4,0.44,0.73,6.55,0.074,38.0,76.0,0.99900,3.17,0.85,12.0,7,502
531,7.3,0.51,0.18,2.10,0.070,12.0,28.0,0.99768,3.52,0.73,9.5,6,745
864,12.6,0.39,0.49,2.50,0.080,8.0,20.0,0.99920,3.07,0.82,10.3,6,1224

In [68]:
df.corr()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
fixed acidity,1.000000,-0.250728,0.673157,0.171831,0.107889,-0.164831,-0.110628,0.681501,-0.685163,0.174592,-0.075055,0.121970,-0.275826
volatile acidity,-0.250728,1.000000,-0.544187,-0.005751,0.056336,-0.001962,0.077748,0.016512,0.221492,-0.276079,-0.203909,-0.407394,-0.007892
citric acid,0.673157,-0.544187,1.000000,0.175815,0.245312,-0.057589,0.036871,0.375243,-0.546339,0.331232,0.106250,0.240821,-0.139011
residual sugar,0.171831,-0.005751,0.175815,1.000000,0.070863,0.165339,0.190790,0.380147,-0.116959,0.017475,0.058421,0.022002,-0.046344
chlorides,0.107889,0.056336,0.245312,0.070863,1.000000,0.015280,0.048163,0.208901,-0.277759,0.374784,-0.229917,-0.124085,-0.088099
free sulfur dioxide,-0.164831,-0.001962,-0.057589,0.165339,0.015280,1.000000,0.661093,-0.054150,0.072804,0.034445,-0.047095,-0.063260,0.095268
total sulfur dioxide,-0.110628,0.077748,0.036871,0.190790,0.048163,0.661093,1.000000,0.050175,-0.059126,0.026894,-0.188165,-0.183339,-0.107389
density,0.681501,0.016512,0.375243,0.380147,0.208901,-0.054150,0.050175,1.000000,-0.352775,0.143139,-0.494727,-0.175208,-0.363926
pH,-0.685163,0.221492,-0.546339,-0.116959,-0.277759,0.072804,-0.059126,-0.352775,1.000000,-0.185499,0.225322,-0.052453,0.132904
sulphates,0.174592,-0.276079,0.331232,0.017475,0.374784,0.034445,0.026894,0.143139,-0.185499,1.000000,0.094421,0.257710,-0.103954
alcohol,-0.075055,-0.203909,0.106250,0.058421,-0.229917,-0.047095,-0.188165,-0.494727,0.225322,0.094421,1.000000,0.484866,0.238087
quality,0.121970,-0.407394,0.240821,0.022002,-0.124085,-0.063260,-0.183339,-0.175208,-0.052453,0.257710,0.484866,1.000000,0.069708
Id,-0.275826,-0.007892,-0.139011,-0.046344,-0.088099,0.095268,-0.107389,-0.363926,0.132904,-0.103954,0.238087,0.069708,1.000000

In [69]:
df.quality.unique()

array([5, 6, 7, 4, 8, 3], dtype=int64)

In [70]:
df.quality.nunique()

6

In [71]:
df.quality.value_counts()

quality
5    483
6    462
7    143
4     33
8     16
3      6
Name: count, dtype: int64

In [72]:
[df.quality>5]
#f[df.quality>5]

[0       False
 1       False
 2       False
 3        True
 4       False
         ...
 1138     True
 1139     True
 1140    False
 1141     True
 1142    False
 Name: quality, Length: 1143, dtype: bool]

In [73]:
df[(df.quality>5) & (df.alcohol>10)]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
12,8.5,0.280,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.5,7,16
26,7.8,0.600,0.14,2.4,0.086,3.0,15.0,0.99750,3.42,0.60,10.8,6,36
30,7.5,0.490,0.20,2.6,0.332,8.0,14.0,0.99680,3.21,0.90,10.5,6,42
38,7.6,0.510,0.15,2.8,0.110,33.0,73.0,0.99550,3.17,0.63,10.2,6,54
48,8.0,0.705,0.05,1.9,0.074,8.0,19.0,0.99620,3.34,0.95,10.5,6,69
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1135,5.8,0.610,0.11,1.8,0.066,18.0,28.0,0.99483,3.55,0.66,10.9,6,1587
1136,6.3,0.550,0.15,1.8,0.077,26.0,35.0,0.99314,3.32,0.82,11.6,6,1590
1137,5.4,0.740,0.09,1.7,0.089,16.0,26.0,0.99402,3.67,0.56,11.6,6,1591
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595

In [74]:
df.alcohol*=1.1
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,10.34,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,10.78,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,10.78,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,10.78,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,10.34,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,12.10,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,10.45,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,11.55,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,12.32,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,11.22,5,1597

In [75]:
def rating(quality):
    if quality>5:
        return "good"
    else:
        return "bad"

In [76]:
df1=df['quality'].apply(rating)
df1

0        bad
1        bad
2        bad
3       good
4        bad
        ...
1138    good
1139    good
1140     bad
1141    good
1142     bad
Name: quality, Length: 1143, dtype: object

In [77]:
df.head(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,10.78,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,10.78,5,2
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,10.78,6,3
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,4

In [80]:
df['quality_level']=df['quality'].map({
    3:'very bad',
    4:'bad',
    5:'good',
    6:'very good',
    7:'nice',
    8:'excellent'})
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality_level
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,0,good
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,10.78,5,1,good
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,10.78,5,2,good
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,10.78,6,3,very good
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,4,good

In [89]:
df['review']=df['quality_level'].map({
    'good':'goody',
    'bad':'badd',
    })
df.head(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality_level,review
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,0,good,goody
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,10.78,5,1,good,goody
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,10.78,5,2,good,goody
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,10.78,6,3,very good,NaN
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,4,good,goody

In [90]:
df['review']=df['quality_level'].replace({
    'good':'goody',
    'bad':'badd',
    })
df.head(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality_level,review
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,0,good,goody
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,10.78,5,1,good,goody
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,10.78,5,2,good,goody
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,10.78,6,3,very good,very good
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,4,good,goody

In [ ]:
#rename
df.rename(columns={'fixed acidity':'acidity',})

,acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality_level,review
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,10.34,5,0,good,goody
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,10.78,5,1,good,goody
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,10.78,5,2,good,goody
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,10.78,6,3,very good,very good
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,10.34,5,4,good,goody
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,12.10,6,1592,very good,very good
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,10.45,6,1593,very good,very good
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,11.55,5,1594,good,goody
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,12.32,6,1595,very good,very good
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,11.22,5,1597,good,goody

In [95]:
df1=pd.read_csv(r'wine_data.csv')
df1

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,WineA,2023-01-10
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,WineC,2023-03-20
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7,205,WineD,2023-04-25
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5,Weingut Syrah Reserve 575,2023-02-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,10.62,0.38,0.41,3.0,0.072,24.8,55.7,0.99732,3.16,0.79,10.99,6,216,Bodega Pinot Classic 513,2024-10-08
216,10.21,0.17,0.60,2.5,0.059,13.7,21.2,0.99388,3.21,0.72,11.25,7,217,Castello Merlot Grand Cru 41,2024-06-03
217,11.29,0.36,0.46,2.8,0.082,26.6,40.2,0.99651,3.27,0.84,11.24,7,218,Bodega Chardonnay Grand Cru 257,2022-02-22
218,9.21,0.36,0.51,2.6,0.082,10.3,19.6,0.99854,3.20,0.70,11.09,6,219,Chateau Cabernet Special 857,2022-02-12
219,10.02,0.21,0.47,1.8,0.050,17.2,33.5,0.99676,3.04,0.70,11.37,7,220,Bodega Sauvignon Classic 591,2022-03-24

In [96]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         220 non-null    float64
 1   volatile acidity      220 non-null    float64
 2   citric acid           220 non-null    float64
 3   residual sugar        220 non-null    float64
 4   chlorides             220 non-null    float64
 5   free sulfur dioxide   220 non-null    float64
 6   total sulfur dioxide  220 non-null    float64
 7   density               220 non-null    float64
 8   pH                    220 non-null    float64
 9   sulphates             220 non-null    float64
 10  alcohol               220 non-null    float64
 11  quality               220 non-null    int64
 12  Id                    220 non-null    int64
 13  name                  220 non-null    object
 14  date                  220 non-null    object
dtypes: float64(11), int64(2), object(2)
memory usage: 25.9+ KB

In [98]:
df1['name']

0                                WineA
1                                WineB
2                                WineC
3                                WineD
4            Weingut Syrah Reserve 575
                    ...
215           Bodega Pinot Classic 513
216       Castello Merlot Grand Cru 41
217    Bodega Chardonnay Grand Cru 257
218       Chateau Cabernet Special 857
219       Bodega Sauvignon Classic 591
Name: name, Length: 220, dtype: object

In [100]:
df1.name.str

In [ ]:
df1.name.str.upper() 
#df1.name.str.lower()

0                                WINEA
1                                WINEB
2                                WINEC
3                                WINED
4            WEINGUT SYRAH RESERVE 575
                    ...
215           BODEGA PINOT CLASSIC 513
216       CASTELLO MERLOT GRAND CRU 41
217    BODEGA CHARDONNAY GRAND CRU 257
218       CHATEAU CABERNET SPECIAL 857
219       BODEGA SAUVIGNON CLASSIC 591
Name: name, Length: 220, dtype: object

In [103]:
df1.name.str.capitalize()

0                                Winea
1                                Wineb
2                                Winec
3                                Wined
4            Weingut syrah reserve 575
                    ...
215           Bodega pinot classic 513
216       Castello merlot grand cru 41
217    Bodega chardonnay grand cru 257
218       Chateau cabernet special 857
219       Bodega sauvignon classic 591
Name: name, Length: 220, dtype: object

In [104]:
df1.name.str.title()

0                                Winea
1                                Wineb
2                                Winec
3                                Wined
4            Weingut Syrah Reserve 575
                    ...
215           Bodega Pinot Classic 513
216       Castello Merlot Grand Cru 41
217    Bodega Chardonnay Grand Cru 257
218       Chateau Cabernet Special 857
219       Bodega Sauvignon Classic 591
Name: name, Length: 220, dtype: object

In [105]:
df1.name.str.len()

0       5
1       5
2       5
3       5
4      25
       ..
215    24
216    28
217    31
218    28
219    28
Name: name, Length: 220, dtype: int64

In [107]:
df1.name.str.contains('WineA')

0       True
1      False
2      False
3      False
4      False
       ...
215    False
216    False
217    False
218    False
219    False
Name: name, Length: 220, dtype: bool

In [109]:
df1[df1.name.str.contains('WineA')]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date
0,8.5,0.28,0.56,1.8,0.092,35.0,103.0,0.9969,3.3,0.75,10.5,7,16,WineA,2023-01-10

In [111]:
# datetime
df1.date.dtype

dtype('O')

In [112]:
df1['date']=pd.to_datetime(df1.date)
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         220 non-null    float64
 1   volatile acidity      220 non-null    float64
 2   citric acid           220 non-null    float64
 3   residual sugar        220 non-null    float64
 4   chlorides             220 non-null    float64
 5   free sulfur dioxide   220 non-null    float64
 6   total sulfur dioxide  220 non-null    float64
 7   density               220 non-null    float64
 8   pH                    220 non-null    float64
 9   sulphates             220 non-null    float64
 10  alcohol               220 non-null    float64
 11  quality               220 non-null    int64
 12  Id                    220 non-null    int64
 13  name                  220 non-null    object
 14  date                  220 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(11), int64(2), object(1)
memory usage: 25.9+ KB

In [113]:
df1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,WineA,2023-01-10
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,WineC,2023-03-20
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7,205,WineD,2023-04-25
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5,Weingut Syrah Reserve 575,2023-02-12

In [115]:
df1['year']=df1.date.dt.year
df1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date,year
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,WineA,2023-01-10,2023
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15,2023
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,WineC,2023-03-20,2023
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7,205,WineD,2023-04-25,2023
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5,Weingut Syrah Reserve 575,2023-02-12,2023

In [116]:
df1['month']=df1.date.dt.month
df1['day']=df1.date.dt.day
df1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date,year,month,day
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,WineA,2023-01-10,2023,1,10
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15,2023,2,15
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,WineC,2023-03-20,2023,3,20
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7,205,WineD,2023-04-25,2023,4,25
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5,Weingut Syrah Reserve 575,2023-02-12,2023,2,12

In [120]:
#add new data
df1.loc[5]

fixed acidity                                  8.72
volatile acidity                               0.56
citric acid                                    0.34
residual sugar                                  0.8
chlorides                                     0.059
free sulfur dioxide                            22.3
total sulfur dioxide                           59.8
density                                     0.99571
pH                                             3.35
sulphates                                      0.79
alcohol                                        9.79
quality                                           4
Id                                                6
name                    Bodega Riesling Special 559
date                            2024-05-09 00:00:00
year                                           2024
month                                             5
day                                               9
Name: 5, dtype: object

In [121]:
df1.loc[len(df1)-1]

fixed acidity                                  10.02
volatile acidity                                0.21
citric acid                                     0.47
residual sugar                                   1.8
chlorides                                       0.05
free sulfur dioxide                             17.2
total sulfur dioxide                            33.5
density                                      0.99676
pH                                              3.04
sulphates                                        0.7
alcohol                                        11.37
quality                                            7
Id                                               220
name                    Bodega Sauvignon Classic 591
date                             2022-03-24 00:00:00
year                                            2022
month                                              3
day                                               24
Name: 219, dtype: object

In [123]:
df1.loc[len(df1)]=[12.45,0.23,0.45,2.0,0.06,18.2,34.1,0.998,3.4,0.8,11.45,8,221,'eggteb urgevww 765',2022-3-26,2022,3,26]

In [124]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 221 entries, 0 to 220
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         221 non-null    float64
 1   volatile acidity      221 non-null    float64
 2   citric acid           221 non-null    float64
 3   residual sugar        221 non-null    float64
 4   chlorides             221 non-null    float64
 5   free sulfur dioxide   221 non-null    float64
 6   total sulfur dioxide  221 non-null    float64
 7   density               221 non-null    float64
 8   pH                    221 non-null    float64
 9   sulphates             221 non-null    float64
 10  alcohol               221 non-null    float64
 11  quality               221 non-null    int64
 12  Id                    221 non-null    int64
 13  name                  221 non-null    object
 14  date                  221 non-null    object
 15  year                  221 non-null    int64
 16  month                 221 non-null    int64
 17  day                   221 non-null    int64
dtypes: float64(11), int64(5), object(2)
memory usage: 32.8+ KB

In [125]:
df1.drop(index=4,inplace=True)

In [128]:
df1.drop(index=[1,2,3],inplace=True)
df1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date,year,month,day
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,WineA,2023-01-10 00:00:00,2023,1,10
5,8.72,0.56,0.34,0.8,0.059,22.3,59.8,0.99571,3.35,0.79,9.79,4,6,Bodega Riesling Special 559,2024-05-09 00:00:00,2024,5,9
6,9.54,0.61,0.41,3.1,0.064,23.5,51.8,0.99716,3.32,0.73,9.15,4,7,Domaine Pinot Grand Cru 285,2022-01-14 00:00:00,2022,1,14
7,9.08,0.63,0.49,1.1,0.072,18.1,42.5,0.99795,3.20,0.81,8.88,3,8,Domaine Riesling Premium 349,2023-07-24 00:00:00,2023,7,24
8,8.88,0.44,0.40,2.9,0.079,15.3,43.6,0.99742,3.42,0.79,10.84,5,9,Domaine Cabernet Classic 105,2022-07-09 00:00:00,2022,7,9

In [129]:
df1.drop(columns='pH',inplace=True)
df1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,sulphates,alcohol,quality,Id,name,date,year,month,day
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,0.75,10.50,7,16,WineA,2023-01-10 00:00:00,2023,1,10
5,8.72,0.56,0.34,0.8,0.059,22.3,59.8,0.99571,0.79,9.79,4,6,Bodega Riesling Special 559,2024-05-09 00:00:00,2024,5,9
6,9.54,0.61,0.41,3.1,0.064,23.5,51.8,0.99716,0.73,9.15,4,7,Domaine Pinot Grand Cru 285,2022-01-14 00:00:00,2022,1,14
7,9.08,0.63,0.49,1.1,0.072,18.1,42.5,0.99795,0.81,8.88,3,8,Domaine Riesling Premium 349,2023-07-24 00:00:00,2023,7,24
8,8.88,0.44,0.40,2.9,0.079,15.3,43.6,0.99742,0.79,10.84,5,9,Domaine Cabernet Classic 105,2022-07-09 00:00:00,2022,7,9

In [130]:
df1['wine_type']='red wine'
df1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,sulphates,alcohol,quality,Id,name,date,year,month,day,wine_type
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,0.75,10.50,7,16,WineA,2023-01-10 00:00:00,2023,1,10,red wine
5,8.72,0.56,0.34,0.8,0.059,22.3,59.8,0.99571,0.79,9.79,4,6,Bodega Riesling Special 559,2024-05-09 00:00:00,2024,5,9,red wine
6,9.54,0.61,0.41,3.1,0.064,23.5,51.8,0.99716,0.73,9.15,4,7,Domaine Pinot Grand Cru 285,2022-01-14 00:00:00,2022,1,14,red wine
7,9.08,0.63,0.49,1.1,0.072,18.1,42.5,0.99795,0.81,8.88,3,8,Domaine Riesling Premium 349,2023-07-24 00:00:00,2023,7,24,red wine
8,8.88,0.44,0.40,2.9,0.079,15.3,43.6,0.99742,0.79,10.84,5,9,Domaine Cabernet Classic 105,2022-07-09 00:00:00,2022,7,9,red wine

In [131]:
df1['high alcohol']=df1.alcohol>=10
df1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,sulphates,alcohol,quality,Id,name,date,year,month,day,wine_type,high alcohol
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,0.75,10.50,7,16,WineA,2023-01-10 00:00:00,2023,1,10,red wine,True
5,8.72,0.56,0.34,0.8,0.059,22.3,59.8,0.99571,0.79,9.79,4,6,Bodega Riesling Special 559,2024-05-09 00:00:00,2024,5,9,red wine,False
6,9.54,0.61,0.41,3.1,0.064,23.5,51.8,0.99716,0.73,9.15,4,7,Domaine Pinot Grand Cru 285,2022-01-14 00:00:00,2022,1,14,red wine,False
7,9.08,0.63,0.49,1.1,0.072,18.1,42.5,0.99795,0.81,8.88,3,8,Domaine Riesling Premium 349,2023-07-24 00:00:00,2023,7,24,red wine,False
8,8.88,0.44,0.40,2.9,0.079,15.3,43.6,0.99742,0.79,10.84,5,9,Domaine Cabernet Classic 105,2022-07-09 00:00:00,2022,7,9,red wine,True

In [138]:
#merge and concat
data1={
    'Name':['A','B','C'],
    'age':[23,45,67],
    'salary':[10000,20000,30000]
}
data2={
    'Name':['A','E','F'],
    'age':[53,42,59],
    'salary':[15000,25000,35000]
}

In [139]:
d1=pd.DataFrame(data1)
d2=pd.DataFrame(data2)
pd.concat([d1,d2])

  Name  age  salary
0    A   23   10000
1    B   45   20000
2    C   67   30000
0    A   53   15000
1    E   42   25000
2    F   59   35000

In [151]:
new_df=pd.concat([d1,d2],ignore_index=True)
new_df

  Name  age  salary
0    A   23   10000
1    B   45   20000
2    C   67   30000
3    A   53   15000
4    E   42   25000
5    F   59   35000

In [148]:
new_df=pd.concat([d1,d2],ignore_index=True)
new_df

  Name  age  salary
0    A   23   10000
1    B   45   20000
2    C   67   30000
3    A   53   15000
4    E   42   25000
5    F   59   35000

In [150]:
new_df.drop_duplicates(inplace=True)
new_df

  Name  age  salary
0    A   23   10000
1    B   45   20000
2    C   67   30000
3    A   53   15000
4    E   42   25000
5    F   59   35000

In [152]:
pd.merge(d1,d2,on='age',how='outer')

  Name_x  age  salary_x Name_y  salary_y
0      A   23   10000.0    NaN       NaN
1    NaN   42       NaN      E   25000.0
2      B   45   20000.0    NaN       NaN
3    NaN   53       NaN      A   15000.0
4    NaN   59       NaN      F   35000.0
5      C   67   30000.0    NaN       NaN