In [2]:
import pandas as pd

In [3]:
df=pd.read_csv(r'tips.csv')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [4]:
df.head(5)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
df.tail(5)

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [6]:
df.sample(5)

     total_bill   tip     sex smoker   day    time  size
203       16.40  2.50  Female    Yes  Thur   Lunch     2
84        15.98  2.03    Male     No  Thur   Lunch     2
104       20.92  4.08  Female     No   Sat  Dinner     2
33        20.69  2.45  Female     No   Sat  Dinner     4
27        12.69  2.00    Male     No   Sat  Dinner     2

In [7]:
df.loc[10:15]

    total_bill   tip     sex smoker  day    time  size
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4
12       15.42  1.57    Male     No  Sun  Dinner     2
13       18.43  3.00    Male     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2
15       21.58  3.92    Male     No  Sun  Dinner     2

In [8]:
df.ndim

2

In [9]:
df.shape

(244, 7)

In [10]:
df.size

1708

In [11]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [13]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [14]:
df['tip'].value_counts(sort=True,ascending=True)

tip
1.01     1
1.73     1
1.63     1
1.36     1
2.30     1
        ..
5.00    10
2.50    10
4.00    12
3.00    23
2.00    33
Name: count, Length: 123, dtype: int64

In [15]:
df.describe(include=float)

       total_bill         tip
count  244.000000  244.000000
mean    19.785943    2.998279
std      8.902412    1.383638
min      3.070000    1.000000
25%     13.347500    2.000000
50%     17.795000    2.900000
75%     24.127500    3.562500
max     50.810000   10.000000

In [17]:
df.describe(include='object')

         sex smoker  day    time
count    244    244  244     244
unique     2      2    4       2
top     Male     No  Sat  Dinner
freq     157    151   87     176

In [18]:
df.dtypes

total_bill    float64
tip           float64
sex            object
smoker         object
day            object
time           object
size            int64
dtype: object

In [19]:
df['total_bill'].dtype

dtype('float64')

In [20]:
df.select_dtypes(include=object)

        sex smoker   day    time
0    Female     No   Sun  Dinner
1      Male     No   Sun  Dinner
2      Male     No   Sun  Dinner
3      Male     No   Sun  Dinner
4    Female     No   Sun  Dinner
..      ...    ...   ...     ...
239    Male     No   Sat  Dinner
240  Female    Yes   Sat  Dinner
241    Male    Yes   Sat  Dinner
242    Male     No   Sat  Dinner
243  Female     No  Thur  Dinner

[244 rows x 4 columns]

In [21]:
df.select_dtypes(include=float).columns

Index(['total_bill', 'tip'], dtype='object')

In [23]:
df.iloc[0:9,0:3]

   total_bill   tip     sex
0       16.99  1.01  Female
1       10.34  1.66    Male
2       21.01  3.50    Male
3       23.68  3.31    Male
4       24.59  3.61  Female
5       25.29  4.71    Male
6        8.77  2.00    Male
7       26.88  3.12    Male
8       15.04  1.96    Male

In [24]:
df['total_bill'][0]

16.99

In [25]:
df.iat[0,2]

'Female'

In [27]:
df.isnull()

     total_bill    tip    sex  smoker    day   time   size
0         False  False  False   False  False  False  False
1         False  False  False   False  False  False  False
2         False  False  False   False  False  False  False
3         False  False  False   False  False  False  False
4         False  False  False   False  False  False  False
..          ...    ...    ...     ...    ...    ...    ...
239       False  False  False   False  False  False  False
240       False  False  False   False  False  False  False
241       False  False  False   False  False  False  False
242       False  False  False   False  False  False  False
243       False  False  False   False  False  False  False

[244 rows x 7 columns]

In [28]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [29]:
df.notnull().sum()

total_bill    244
tip           244
sex           244
smoker        244
day           244
time          244
size          244
dtype: int64

In [30]:
df.dropna()

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [31]:
df.fillna(df.mean)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [32]:
df.duplicated().sum()

1

In [33]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Length: 244, dtype: bool

In [34]:
df.sort_values(by='total_bill')

     total_bill    tip     sex smoker   day    time  size
67         3.07   1.00  Female    Yes   Sat  Dinner     1
92         5.75   1.00  Female    Yes   Fri  Dinner     2
111        7.25   1.00  Female     No   Sat  Dinner     1
172        7.25   5.15    Male    Yes   Sun  Dinner     2
149        7.51   2.00    Male     No  Thur   Lunch     2
..          ...    ...     ...    ...   ...     ...   ...
182       45.35   3.50    Male    Yes   Sun  Dinner     3
156       48.17   5.00    Male     No   Sun  Dinner     6
59        48.27   6.73    Male     No   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
170       50.81  10.00    Male    Yes   Sat  Dinner     3

[244 rows x 7 columns]

In [35]:
df.sample(5).sort_index()

     total_bill   tip     sex smoker   day    time  size
40        16.04  2.24    Male     No   Sat  Dinner     3
131       20.27  2.83  Female     No  Thur   Lunch     2
186       20.90  3.50  Female    Yes   Sun  Dinner     3
233       10.77  1.47    Male     No   Sat  Dinner     2
240       27.18  2.00  Female    Yes   Sat  Dinner     2

In [36]:
df.sample(5,ignore_index=False).sort_index(ascending=True)

     total_bill   tip     sex smoker   day    time  size
56        38.01  3.00    Male    Yes   Sat  Dinner     4
70        12.02  1.97    Male     No   Sat  Dinner     2
111        7.25  1.00  Female     No   Sat  Dinner     1
205       16.47  3.23  Female    Yes  Thur   Lunch     3
225       16.27  2.50  Female    Yes   Fri   Lunch     2

In [39]:
#df.corr()
#it will not work as there are object values in the dataset

In [44]:
#df.size.unique() it will not run as 'size' is a keyword and it will conflict
df['size'].unique()

array([2, 3, 4, 1, 6, 5], dtype=int64)

In [45]:
df['size'].nunique()

6

In [46]:
df['size'].value_counts()

size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

In [49]:
df['size']>2

0      False
1       True
2       True
3      False
4       True
       ...
239     True
240    False
241    False
242    False
243    False
Name: size, Length: 244, dtype: bool

In [54]:
df.mode()

   total_bill  tip   sex smoker  day    time  size
0       13.42  2.0  Male     No  Sat  Dinner     2

In [55]:
df['size'].apply(lambda x: x*2)

0      4
1      6
2      6
3      4
4      8
      ..
239    6
240    4
241    4
242    4
243    4
Name: size, Length: 244, dtype: int64

In [58]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4